# WorkFlow Do: install Python dependencies, run tests and linter, and return code coverage  
name: CI - Workflow
on: push
jobs:  
  
  build:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install Requirements and Dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[test]
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Clean-Up Environment
        run: |
#          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#          chmod +x ./cc-test-reporter
          rm -rf .coverage
          coverage erase

      - name: Run Tests
        run: |
          pytest --cov=omop2obo --cov-report xml:coverage.xml
          coverage report
          coverage xml
          python-codacy-coverage -r coverage.xml
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Linting with Mypy
        run: mypy --strict-optional omop2obo

      - name: print outputs
        run: |
          ls -la
          ls -la .coverage

      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@master
        with:
          name: code-coverage-report
          path: |
            coverage.xml
            .coverage

  sonarCloudTrigger:
    needs: build
    name: Sonar Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # disabling shallow clone improves relevancy of reporting

      - name: Download Code Coverage Results
        uses: actions/download-artifact@master
        with:
          name: code-coverage-report
          path: |
            coverage.xml
            .coverage

      - name: Sonar Cloud Scanner
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  codacyTrigger:
    needs: build
    name: Codacy
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # disabling shallow clone improves relevancy of reporting

      - name: Download Code Coverage Results
        uses: actions/download-artifact@master
        with:
          name: code-coverage-report
          path: coverage.xml

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

  codeClimateTrigger:
    needs: build
    name: Code Climate
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # disabling shallow clone improves relevancy of reporting

      - name: Set-Up Envrionment
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Download Code Coverage Results
        uses: actions/download-artifact@master
        with:
          name: code-coverage-report
          path: .coverage

      - name: Publish Coverage to Code Climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{github.workspace}}/.coverage

  coverallsTrigger:
    needs: build
    name: Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # disabling shallow clone improves relevancy of reporting

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Complete Coveralls
        run: |
          pip install --upgrade pip coveralls setuptools
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
