# WorkFlow Do: install Python dependencies, run tests and linter, and return code coverage  
name: CI - Workflow
on: push
jobs:  
  
  build:
    name: Quality Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install Requirements and Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Run Tests and Ouput Coverage Report
        run: |
          pytest --cov=omop2obo --cov-report xml:coverage.xml
          coverage combine --append || true
          coverage report
          coverage xml

      - name: Linting with Mypy
        run: mypy --strict-optional omop2obo
        
      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@master
        with:
          name: code-coverage-report
          path: coverage.xml
      
  sonarCloudTrigger:
    needs: build
    name: Coverage Trigger
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # disabling shallow clone improves relevancy of reporting

      - name: Download Code Coverage Results
        uses: actions/download-artifact@master
        with:
          name: code-coverage-report
          path: coverage.xml
        
      - name: Sonar Cloud   
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  codacyTrigger:
    needs: build
    name: Coverage Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # disabling shallow clone improves relevancy of reporting

      - name: Download Code Coverage Results
        uses: actions/download-artifact@master
        with:
          name: code-coverage-report
          path: coverage.xml

      - name: Codacy CLI Analysis
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  codeClimateTrigger:
    needs: build
    name: Coverage Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # disabling shallow clone improves relevancy of reporting

      - name: Download Code Coverage Results
        uses: actions/download-artifact@master
        with:
          name: code-coverage-report
          path: coverage.xml

      - name: CodeClimate
        uses: paambaati/codeclimate-action@master
        with:
          command: echo 'Uploading Test Coverage'
          reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}

  coverallsTrigger:
    needs: build
    name: Coverage Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # disabling shallow clone improves relevancy of reporting

      - name: Download Code Coverage Results
        uses: actions/download-artifact@master
        with:
          name: code-coverage-report
          path: coverage.xml

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
